In [ ]:
import pandas as pd

In [ ]:
s1 = pd.Series([1,2,3,4])
s1

In [ ]:
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3})
s2

In [ ]:
s2.values

In [ ]:
dict = {'a': 1, 'b': 2, 'c': 3}
obj3 = pd.Series(dict)
obj3

In [ ]:
import pandas as pd
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002,2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
Frame = pd.DataFrame(data)
Frame

In [ ]:
Frame.head()

In [ ]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

In [ ]:
obj3 = pd.Series(range(3), index = ['a', 'b', 'c'])

In [ ]:
index = obj3.index
index

In [ ]:
idx = pd.Index(['x', 'y', 'z'])
idx

In [ ]:
import numpy as np
res1 = np.arange(3)
res1

In [ ]:
import pandas as pd
res2 = pd.Series(range(3), index = ['a','b', 'c'])
res2

In [ ]:
import numpy as np
labels = pd.Index(np.arange(3))
labels

In [ ]:
abc = pd.Series([3, -1, 4], index = labels)
abc

In [ ]:
import pandas as pd
obj = pd.Series([2, 3, 4, -3], index = ['b', 'd','a', 'c'])
obj

In [ ]:
obj2 = obj.reindex(['y', 't', 'a', 'b','c', 'd'])
obj2

In [ ]:
obj3 = pd.Series(['blue', 'red', 'yellow'], index = [0,2,4])
obj3

In [ ]:
obj3.reindex(range(6), method = 'ffill')

In [ ]:
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape(3, 3),
                     index = ['a', 'c', 'd'],
                     columns = ['Ohio', 'Texas', 'California'])
frame

In [ ]:
frame.reindex(['a', 'c', 'd', 'e', 'f'])

In [ ]:
state = ['Ohio', 'Melbourne', 'California']
frame.reindex(columns = state)

In [ ]:
obj = pd.Series(np.arange(5), index = ['a', 'b', 'c', 'd', 'e'])
obj

In [ ]:
obj6 = obj.drop('c')
obj6

In [ ]:
import pandas as pd
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj6 = obj.drop('c')  
obj6

In [ ]:
new_frame = pd.DataFrame(np.arange(16).reshape(4, 4),
                         index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                         columns = ['One', "Two", 'Three', 'Four'])
new_frame

In [ ]:
new_frame.drop(['Ohio', 'Colorado'])

In [ ]:
new_frame.drop('Two', axis = 1)

In [ ]:
new_frame.loc['Colorado', ['Three', 'Four']]

In [ ]:
new_frame.iloc[2, [3, 0, 1]]

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape(3,4),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4,5),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan #把第一行的b列设置成NaN

df2

In [ ]:
df1 + df2

In [ ]:
df1.add(df2, fill_value=0) #对 df1 执行加法操作， 加上 df2， 如果某个位置在其中一个 DataFrame 中缺失，就用 0 填充后再计算

In [ ]:
import os
os.makedirs('examples')

In [ ]:
csv_content = """
a, b, c, d, message
1, 2, 3, 4, hello
5, 6, 7, 8, world
9, 10, 11, 12, foo """

In [ ]:
with open ('example', 'w') as f:
    f.write(csv_content)

In [ ]:
!cat examples #查看文件

In [ ]:
import pandas as pd
pd.read_table('examples.csv', sep = ',')

In [1]:
import pandas as pd
import os

In [3]:
os.makedirs('examples', exist_ok = True)

In [10]:
csv_content = """a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo
"""

In [11]:
file_path = 'examples/example.csv'
with open('example', 'w') as f:
    f.write(csv_content)

In [ ]:
pd.read_table('example', sep = ',') #使用 pandas 读取名为 'example' 的文件，并按照逗号分隔符解析成表格数据

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [17]:
pd.read_csv('example', names = ['z', 'x', 'c', 'v', 'text'])

   z   x   c   v     text
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [18]:
import json

In [23]:
json_content = '''[
    {"a": 1, "b": 2, "c": 3, "d": 4, "message": "hello"},
    {"a": 5, "b": 6, "c": 7, "d": 8, "message": "world"},
    {"a": 9, "b": 10, "c": 11, "d": 12, "message": "foo"}
]'''

In [27]:
with open ('example.json', 'w') as f:
    f.write(json_content)

In [ ]:
result = json.loads(json_content) #将 JSON 格式的字符串转换为 Python 对象
result

[{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'message': 'hello'},
 {'a': 5, 'b': 6, 'c': 7, 'd': 8, 'message': 'world'},
 {'a': 9, 'b': 10, 'c': 11, 'd': 12, 'message': 'foo'}]

In [ ]:
asjson = json.dumps(result) #将Python对象转回JSON
asjson

'[{"a": 1, "b": 2, "c": 3, "d": 4, "message": "hello"}, {"a": 5, "b": 6, "c": 7, "d": 8, "message": "world"}, {"a": 9, "b": 10, "c": 11, "d": 12, "message": "foo"}]'

In [34]:
result = json.loads(json_content) #将 JSON 格式的字符串转换为 Python 对象
result

[{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'message': 'hello'},
 {'a': 5, 'b': 6, 'c': 7, 'd': 8, 'message': 'world'},
 {'a': 9, 'b': 10, 'c': 11, 'd': 12, 'message': 'foo'}]

In [35]:
result_dict = {
    "data": result,  # 把你的数据放在 'data' 键下
    "siblings": [    # 添加siblings数据，以便使用书上代码
        {"name": "Alice", "age": 28},
        {"name": "Bob", "age": 25},
        {"name": "Charlie", "age": 22}
    ]
}

In [ ]:
siblings = pd.DataFrame(result_dict['siblings'], columns=['name', 'age'])
siblings
# 从result_dict中取出'siblings'键对应的列表数据，创建DataFrame，并且只保留'name'和'age'这两列

      name  age
0    Alice   28
1      Bob   25
2  Charlie   22

In [41]:
! cat examples/example.json

4590.54s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

cat: examples/example.json: No such file or directory

In [42]:
import os

# 检查文件是否存在
file_path = 'examples/example.json'
print(f"检查文件: {file_path}")

if os.path.exists(file_path):
    print("✅ 文件存在")
    # 查看文件大小
    size = os.path.getsize(file_path)
    print(f"文件大小: {size} 字节")
    
    # 用Python读取文件内容
    with open(file_path, 'r') as f:
        content = f.read()
        print(f"文件内容前200字符:\n{content[:200]}")
else:
    print("❌ 文件不存在")
    
    # 查看examples目录是否存在
    if os.path.exists('examples'):
        print("examples目录存在，包含的文件:")
        for f in os.listdir('examples'):
            print(f"  - {f}")
    else:
        print("examples目录也不存在")

检查文件: examples/example.json
❌ 文件不存在
examples目录存在，包含的文件:

In [43]:
import os
import json

In [44]:
os.makedirs('examples', exist_ok = True)
data = [
    {"a": 1, "b": 2, "c": 3, "d": 4, "message": "hello"},
    {"a": 5, "b": 6, "c": 7, "d": 8, "message": "world"},
    {"a": 9, "b": 10, "c": 11, "d": 12, "message": "foo"}
]

In [46]:
file_path = 'examples/example.json'
with open(file_path, 'w') as f:
    json.dump(data, f, indent=2)  # indent=2 让 JSON 格式更美观

In [ ]:
! cat examples/example.json # 在系统终端中执行 cat 命令，显示 examples/example.json 文件的内容

4901.57s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

[
  {
    "a": 1,
    "b": 2,
    "c": 3,
    "d": 4,
    "message": "hello"
  },
  {
    "a": 5,
    "b": 6,
    "c": 7,
    "d": 8,
    "message": "world"
  },
  {
    "a": 9,
    "b": 10,
    "c": 11,
    "d": 12,
    "message": "foo"
  }
]

In [48]:
!conda install lxml -y
!pip install beautifulsoup4 html5lib

6887.05s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

zsh:1: command not found: conda

6892.35s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

zsh:1: /Users/wangjingxuan/Jingxuan Wang/.venv/bin/pip: bad interpreter: /Users/wangjingxuan/Jingxuan: no such file or directory
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (4.14.3)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: soupsieve>=1.6.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1

In [54]:
import sys
import subprocess

print(f"当前Python解释器: {sys.executable}")
print(f"当前工作目录: {sys.path[0]}")

# 使用sys.executable来确保使用正确的Python
def safe_install(package):
    """安全安装包，避免路径空格问题"""
    cmd = [sys.executable, "-m", "pip", "install", package]
    print(f"执行: {' '.join(cmd)}")
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"✅ {package} 安装成功")
            return True
        else:
            print(f"❌ {package} 安装失败")
            print(f"错误: {result.stderr[:200]}")
            return False
    except Exception as e:
        print(f"安装异常: {e}")
        return False

# 安装需要的包
packages = ['lxml', 'beautifulsoup4', 'html5lib']
for package in packages:
    safe_install(package)

当前Python解释器: /Users/wangjingxuan/Jingxuan Wang/.venv/bin/python3
当前工作目录: /Library/Frameworks/Python.framework/Versions/3.13/lib/python313.zip
执行: /Users/wangjingxuan/Jingxuan Wang/.venv/bin/python3 -m pip install lxml
✅ lxml 安装成功
执行: /Users/wangjingxuan/Jingxuan Wang/.venv/bin/python3 -m pip install beautifulsoup4
✅ beautifulsoup4 安装成功
执行: /Users/wangjingxuan/Jingxuan Wang/.venv/bin/python3 -m pip install html5lib
✅ html5lib 安装成功

In [4]:
import os

file_path = 'examples/fdict_failed_bank_list.html'
print(f"检查文件: {file_path}")

if os.path.exists(file_path):
    print("✅ 文件存在")
    
    # 查看文件大小
    size = os.path.getsize(file_path)
    print(f"文件大小: {size} 字节")
    
    # 查看文件内容前500字符
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read(500)
        print(f"\n文件内容前500字符:")
        print(content)
        
        # 检查是否有table标签
        if '<table' in content.lower():
            print("✅ 文件中包含<table>标签")
        else:
            print("❌ 文件中没有找到<table>标签")
else:
    print("❌ 文件不存在")
    
    # 列出examples目录内容
    if os.path.exists('examples'):
        print("\nexamples目录中的文件:")
        for file in os.listdir('examples'):
            print(f"  - {file}")
    else:
        print("\nexamples目录也不存在")

检查文件: examples/fdict_failed_bank_list.html
❌ 文件不存在

examples目录中的文件:
  - example.json

In [5]:
import os
import pandas as pd

# 1. 确保目录存在
os.makedirs('examples', exist_ok=True)

# 2. 创建示例HTML文件（包含表格）
html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>FDIC Failed Bank List - Example</title>
</head>
<body>
    <h1>FDIC Failed Bank List (示例数据)</h1>
    
    <table border="1" class="dataframe">
        <thead>
            <tr style="text-align: right;">
                <th>Bank Name</th>
                <th>City</th>
                <th>State</th>
                <th>CERT</th>
                <th>Acquiring Institution</th>
                <th>Closing Date</th>
                <th>Fund</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>First Republic Bank</td>
                <td>San Francisco</td>
                <td>CA</td>
                <td>59017</td>
                <td>JPMorgan Chase Bank</td>
                <td>May 1, 2023</td>
                <td>105107</td>
            </tr>
            <tr>
                <td>Signature Bank</td>
                <td>New York</td>
                <td>NY</td>
                <td>57053</td>
                <td>Flagstar Bank</td>
                <td>March 12, 2023</td>
                <td>105175</td>
            </tr>
            <tr>
                <td>Silicon Valley Bank</td>
                <td>Santa Clara</td>
                <td>CA</td>
                <td>34255</td>
                <td>First-Citizens Bank</td>
                <td>March 10, 2023</td>
                <td>105134</td>
            </tr>
            <tr>
                <td>Almena State Bank</td>
                <td>Almena</td>
                <td>KS</td>
                <td>15426</td>
                <td>Equity Bank</td>
                <td>October 23, 2020</td>
                <td>10537</td>
            </tr>
            <tr>
                <td>First City Bank of Florida</td>
                <td>Fort Walton Beach</td>
                <td>FL</td>
                <td>16748</td>
                <td>United Fidelity Bank</td>
                <td>October 16, 2020</td>
                <td>10536</td>
            </tr>
        </tbody>
    </table>
    
    <p>数据来源: FDIC Failed Bank List</p>
</body>
</html>
"""

# 3. 保存文件（注意正确的文件名）
file_path = 'examples/fdic_failed_bank_list.html'  # 注意是 fdic，不是 fdict
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(html_content)

print(f"✅ 已创建示例文件: {file_path}")
print(f"文件大小: {os.path.getsize(file_path)} 字节")

# 4. 立即测试读取
print("\n测试读取文件...")
try:
    tables = pd.read_html(file_path)
    print(f"✅ 读取成功！找到 {len(tables)} 个表格")
    
    # 显示表格信息
    df = tables[0]
    print(f"\n表格形状: {df.shape}")
    print(f"列名: {list(df.columns)}")
    print("\n前3行数据:")
    print(df.head(3))
    
except Exception as e:
    print(f"❌ 读取失败: {e}")

✅ 已创建示例文件: examples/fdic_failed_bank_list.html
文件大小: 2086 字节

测试读取文件...
✅ 读取成功！找到 1 个表格

表格形状: (5, 7)
列名: ['Bank Name', 'City', 'State', 'CERT', 'Acquiring Institution', 'Closing Date', 'Fund']

前3行数据:
             Bank Name           City State   CERT Acquiring Institution  \
0  First Republic Bank  San Francisco    CA  59017   JPMorgan Chase Bank
1       Signature Bank       New York    NY  57053         Flagstar Bank
2  Silicon Valley Bank    Santa Clara    CA  34255   First-Citizens Bank

     Closing Date    Fund
0     May 1, 2023  105107
1  March 12, 2023  105175
2  March 10, 2023  105134

In [3]:
import pandas as pd
tables = pd.read_html('examples/fdic_failed_bank_list.html')
len(tables)

1

In [4]:
df = tables[0]
print(f"{df.shape}") # 表格形状

(5, 7)

In [5]:
failure = tables[0]
print(type(failure))
failure.head()

<class 'pandas.core.frame.DataFrame'>

,Bank Name,City,State,CERT,Acquiring Institution,Closing Date,Fund
0,First Republic Bank,San Francisco,CA,59017,JPMorgan Chase Bank,"May 1, 2023",105107
1,Signature Bank,New York,NY,57053,Flagstar Bank,"March 12, 2023",105175
2,Silicon Valley Bank,Santa Clara,CA,34255,First-Citizens Bank,"March 10, 2023",105134
3,Almena State Bank,Almena,KS,15426,Equity Bank,"October 23, 2020",10537
4,First City Bank of Florida,Fort Walton Beach,FL,16748,United Fidelity Bank,"October 16, 2020",10536

In [6]:
close_num = pd.to_datetime(failure['Closing Date']) 
# 将 failure DataFrame 中的 'Closing Date' 列转换为 pandas 的 datetime 类型
print(type(close_num))
close_num

<class 'pandas.core.series.Series'>

0   2023-05-01
1   2023-03-12
2   2023-03-10
3   2020-10-23
4   2020-10-16
Name: Closing Date, dtype: datetime64[ns]

In [7]:
close_num.dt.year.value_counts()
# close_num 这是一个 Series，包含转换后的日期时间数据
# .dt 日期时间访问器（datetime accessor）
# .dt.year 提取每个日期的年份
# .value_counts() 统计每个唯一值出现的次数

Closing Date
2023    3
2020    2
Name: count, dtype: int64

In [12]:
import os
path = 'examples/mta_perf/Performance_MNR.xml'
print(f"当前工作目录: {os.getcwd()}")
print(f"文件是否存在: {os.path.exists(path)}")

当前工作目录: /Users/wangjingxuan/Jingxuan Wang/data
文件是否存在: False

In [ ]:
import os   
os.makedirs('examples/mta_perf', exist_ok=True)

xml_content = '''<INDICATOR>
    <INDICATOR_SEQ>373889</INDICATOR_SEQ>
    <PARENT_SEQ></PARENT_SEQ>

    <AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
    <INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
    <DESCRIPTION>Percent of the time that escalators are operational systemwide. The availability rate is based on physical observations performed the morning of regular business days only. This is a new indicator the agency began reporting in 2009.</DESCRIPTION>
    <PERIOD_YEAR>2011</PERIOD_YEAR>
    <PERIOD_MONTH>12</PERIOD_MONTH>
    <CATEGORY>Service Indicators</CATEGORY>
    <FREQUENCY>M</FREQUENCY>

    <DESIRED_CHANGE>U</DESIRED_CHANGE>
    <INDICATOR_UNIT>%</INDICATOR_UNIT>
    <DECIMAL_PLACES>1</DECIMAL_PLACES>
    
    <YTD_TARGET>97.00</YTD_TARGET>
    <YTD_ACTUAL></YTD_ACTUAL>
    <MONTHLY_TARGET>97.00</MONTHLY_TARGET>
    <MONTHLY_ACTUAL></MONTHLY_ACTUAL>
</INDICATOR>'''
with open ('examples/mta_perf/Performance_MNR.xml', 'w') as f:
    f.write(xml_content)

print(f"Sample file has been created: {path}")

Sample file has been created: examples/mta_perf/Performance_MNR.xml

In [25]:
df = pd.read_xml('examples/mta_perf/Performance_MNR.xml', xpath = '//INDICATOR')
df

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,12,Service Indicators,M,U,%,1,97.0,NaN,97.0,NaN

In [22]:
import os
path = 'examples/mta_perf/Performance_MNR.xml'
if os.path.exists(path):
    full_path = os.path.abspath(path) # # 将相对路径转换为绝对路径 绝对路径 - 完整的系统路径  
    print(f'The full path is: {full_path}')

The full path is: /Users/wangjingxuan/Jingxuan Wang/data/examples/mta_perf/Performance_MNR.xml

In [23]:
from lxml import objectify
# 从 lxml 库中导入 objectify 模块
# lxml：一个强大的 Python XML 处理库
# objectify：lxml 的一个子模块，专门用于将 XML 文档转换为 Python 对象
path = 'examples/mta_perf/Performance_MNR.xml'
# 定义一个字符串变量 path，保存 XML 文件的相对路径。
parsed = objectify.parse(open(path))
# open()：Python 内置函数，打开文件
# 解析 XML 文件，返回一个 ElementTree 对象
root = parsed.getroot()

In [28]:
from lxml import objectify
import pandas as pd

# 读取XML文件
xml = objectify.parse('examples/mta_perf/Performance_MNR.xml')  # 替换为你的文件名
root = xml.getroot()

print("根元素标签:", root.tag)
print("根元素的直接子元素:")
for child in root.getchildren():
    print(f"  - {child.tag}")
    
# 查看有多少个INDICATOR元素
all_indicators = root.findall('.//INDICATOR')
print(f"\n找到 {len(all_indicators)} 个INDICATOR元素")

根元素标签: INDICATOR
根元素的直接子元素:
  - INDICATOR_SEQ
  - PARENT_SEQ
  - AGENCY_NAME
  - INDICATOR_NAME
  - DESCRIPTION
  - PERIOD_YEAR
  - PERIOD_MONTH
  - CATEGORY
  - FREQUENCY
  - DESIRED_CHANGE
  - INDICATOR_UNIT
  - DECIMAL_PLACES
  - YTD_TARGET
  - YTD_ACTUAL
  - MONTHLY_TARGET
  - MONTHLY_ACTUAL

找到 0 个INDICATOR元素

In [34]:
from lxml import objectify

xml = objectify.parse('examples/mta_perf/Performance_MNR.xml')
# # objectify.parse() 读取 XML 文件并返回一个对象树
root = xml.getroot()  
# getroot() 方法返回 XML 树的根元素
# 根据你的输出，这个根元素就是 <INDICATOR>
print(f"根元素是: {root.tag}") 
# # root.tag 获取根元素的标签名

根元素是: INDICATOR

In [35]:
# 因为root就是INDICATOR，所以不需要循环
skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ', 'DESIRED_CHANGE', 'DECIMAL_PLACES']

el_data = {}
for child in root.getchildren():  # 直接遍历根元素的子元素
    if child.tag in skip_fields:
        continue
    # 处理值
    if child.text is None:
        value = ''
    else:
        value = child.text.strip()
    el_data[child.tag] = value

print("提取的数据:")
for key, value in el_data.items():
    print(f"{key}: {value}")

# 如果要放入列表（保持与其他代码兼容）
data = [el_data]
print(data)

提取的数据:
AGENCY_NAME: Metro-North Railroad
INDICATOR_NAME: Escalator Availability
DESCRIPTION: Percent of the time that escalators are operational systemwide. The availability rate is based on physical observations performed the morning of regular business days only. This is a new indicator the agency began reporting in 2009.
PERIOD_YEAR: 2011
PERIOD_MONTH: 12
CATEGORY: Service Indicators
FREQUENCY: M
INDICATOR_UNIT: %
YTD_TARGET: 97.00
YTD_ACTUAL:
MONTHLY_TARGET: 97.00
MONTHLY_ACTUAL:
[{'AGENCY_NAME': 'Metro-North Railroad', 'INDICATOR_NAME': 'Escalator Availability', 'DESCRIPTION': 'Percent of the time that escalators are operational systemwide. The availability rate is based on physical observations performed the morning of regular business days only. This is a new indicator the agency began reporting in 2009.', 'PERIOD_YEAR': '2011', 'PERIOD_MONTH': '12', 'CATEGORY': 'Service Indicators', 'FREQUENCY': 'M', 'INDICATOR_UNIT': '%', 'YTD_TARGET': '97.00', 'YTD_ACTUAL': '', 'MONTHLY_TARGET': '97.00', 'MONTHLY_ACTUAL': ''}]

In [39]:
perf = pd.DataFrame(data)
perf

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,12,Service Indicators,M,%,97.00,,97.00,

In [ ]:
import os
os.makedirs('examples', exist_ok=True)
data = {
    'a': [1, 5, 9],
    'b': [2, 6, 10],
    'c': [3, 7, 11],
    'd': [4, 8, 12],
    'message': ['hello', 'world', 'foo']
}

#  保存为CSV
df = pd.DataFrame(data)
df.to_csv('examples/ex1.csv', index=False)

frame = pd.read_csv('examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [47]:

pd.read_pickle('examples/frame_pickle') # 读取文件

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo